import "./globals.css";
import Link from "next/link";

export const metadata = {
    title: "Web tutorials",
    description: "Generated by Mj",
};

export default async function RootLayout({children}) {
    const resp = await fetch('http://localhost:9999/posts');
    const posts = await resp.json();

    return (
        <html>
        <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
            {posts.map((post, index) => (
                <li key={index}>
                    <Link href={`/read/${post.id}`}>{post.title}</Link>
                </li>
            ))}
        </ol>
        {children}
        <ul>
            <li><Link href="/create">Create</Link></li>
            <li><Link href="/update/1">Update</Link></li>
            <li><input type="button" value="delete" /></li>
        </ul>
        </body>
        </html>
    );
}
