import "./globals.css";
import Link from "next/link";
import {Control} from "@/app/Control";

export const metadata = {
    title: "Web tutorials",
    description: "Generated by Mj",
};


export default async function RootLayout({children}) {
    const resp = await fetch('http://localhost:9999/posts', { cache: 'no-store' });
    const posts = await resp.json();

    return (
        <html>
        <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
            {posts.map((post, index) => (
                <li key={index}>
                    <Link href={`/read/${post.id}`}>{post.title}</Link>
                </li>
            ))}
        </ol>
        {children}
        <Control/>
        </body>
        </html>
    );
}
